### ISSUE TITLE
Use the same version of Gradle wrapper for `smoke-tests`

### ISSUE THREAD

**Issue by alexander-yevsyukov** [SpineEventEngine/base#194]
We need to have a Gradle wrapper for running smoke tests and have it the same version as in the main build. Otherwise, we're going to face interesting bugs sooner or later.

So, we need to update `gradle/wrapper` and `tools/smoke-tests/gradle/wrapper` and corresponding shell scripts together.

Options are:

  1. Special shell script in the root directory, which would do

  ```bash
  ./gradlew wrapper --gradle-version 4.10.1
  ./tools/smoke-tests/gradlew wrapper --gradle-version 4.10.1
  ```

  2. Updating the wrapper for smoke-tests from within the build.
  3. Something else?

**Comment by alexander-yevsyukov** [comment]
@dmdashenkov, isn't it already fixed by the recently introduced `buildSrc` arrangement?

**Comment by dmdashenkov** [comment]
It seems like `smoke-tests` still have their own Gradle wrapper.

**Comment by alexander-yevsyukov** [comment]
No longer relevant.
